[tools]
atuin = "latest"
bat = "latest"
btop = "latest"
claude-code = "latest"
duf = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
glow = "latest"
herdr = "latest"
hunk = "latest"
jq = "latest"
lazydocker = "latest"
lazygit = "latest"
neovim = "latest"
opencode = "latest"
ripgrep = "latest"
starship = "latest"
tmux = "latest"
worktrunk = "latest"
yazi = "latest"
yq = "latest"
xh = "latest"
zoxide = "latest"

go = "latest"
node = "lts"
python = "latest"
rust = "latest"
