[tools]
node = "lts"
python = "latest"
go = "latest"

# .config/
neovim = "latest"
tmux = "latest"
yazi = "latest"
starship = "latest"
lazygit = "latest"
lazydocker = "latest"
btop = "latest"
hunk = "latest"

# .
eza = "latest"
gh = "latest"
zoxide = "latest"
ripgrep = "latest"
jq = "latest"
fzf = "latest"
fd = "latest"
bat = "latest"
atuin = "latest"
worktrunk = "latest"

# ai
opencode = "latest"
claude-code = "latest"
