[tools]
atuin = "latest"
bat = "latest"
btop = "latest"
duf = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
glow = "latest"
hunk = "latest"
jq = "latest"
lazydocker = "latest"
lazygit = "latest"
neovim = "latest"
ripgrep = "latest"
starship = "latest"
yazi = "latest"
tmux = "latest"
tree-sitter = "latest"
worktrunk = "latest"
yq = "latest"
xh = "latest"
zoxide = "latest"

# langs
rust = "latest"
