[tools]
bat = "latest"
btop = "latest"
duf = "latest"
eza = "latest"
fzf = "latest"
gh = "latest"
jq = "latest"
lazygit = "latest"
neovim = "latest"
python = "latest"
ripgrep = "latest"
starship = "latest"
yazi = "latest"
yg = "latest"
